const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..');
const storage=fs.readFileSync(path.join(root,'js/storage.js'),'utf8');
const tournament=fs.readFileSync(path.join(root,'js/tournament.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');

assert.match(storage,/categoryScopedPersistence:\s*false/,'category-scoped runtime mode is disabled');
assert.ok(html.indexOf('js/categoryPersistenceAdapter.js')<html.indexOf('js/storage.js'),'cloud adapter loads before storage module');
assert.match(storage,/async loadRemoteIntoApp\(\)[\s\S]*BADMINTON_CATEGORY_PERSISTENCE\.loadMaster\(this\.client,this\.clubId/,'online startup loads the complete cloud master');
assert.match(storage,/loadRemoteIntoApp\(\)[\s\S]*applySnapshot\(loaded\.master\)[\s\S]*BADMINTON_LOCAL\?\.write\(JSON\.stringify\(loaded\.master\)\)/,'successful cloud load replaces local storage with cloud data');
assert.match(storage,/loadRemoteIntoApp\(\)[\s\S]*this\.queueClear\(\)/,'successful cloud login discards stale local cloud queue');
assert.match(storage,/async completeCloudStartup\(\)[\s\S]*loadRemoteIntoApp\(\)[\s\S]*loadLocalFallback\(\)/,'startup uses local data only when cloud loading fails');
assert.match(storage,/queueSave\(snapshot,options=\{\}\)[\s\S]*replaceMaster\(this\.client,[\s\S]*master,[\s\S]*sharedData/,'normal save uploads the complete master snapshot');
assert.doesNotMatch(storage,/queueSave\(snapshot,options=\{\}\)[\s\S]*queueCategoryScopedSave/,'normal save does not route through category-scoped saving');
assert.match(storage,/async syncPending\(\)[\s\S]*replaceMaster\(this\.client,[\s\S]*master:q\.snapshot/,'offline queue retries the complete master snapshot');
assert.match(storage,/window\.BADMINTON_LOCAL\?\.write\(JSON\.stringify\(loaded\.master\)\)/,'successful cloud retry refreshes local cache from cloud');
assert.match(tournament,/saveLocal\(true,\{replaceAll:true,allowCategoryRemoval:true\}\)/,'category-list changes explicitly declare category removal');
assert.match(tournament,/allowEmptyOverwrite:true,allowCategoryRemoval:true/,'intentional reset/import explicitly declare destructive replacement');
assert.match(tournament,/category rename is metadata\/category-scoped work[\s\S]*saveLocal\(true\);/,'category rename does not need a special scoped save path');
console.log('PASS: cloud is authoritative on successful startup/login');
console.log('PASS: local storage is fallback only when cloud is unavailable');
console.log('PASS: every normal save uploads the complete master snapshot');
console.log('PASS: offline retry uploads the complete queued master snapshot');
console.log('PASS: destructive full-master operations explicitly declare their intent');
