const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..');const storage=fs.readFileSync(path.join(root,'js/storage.js'),'utf8');const tournament=fs.readFileSync(path.join(root,'js/tournament.js'),'utf8');const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(storage,/categoryScopedPersistence:\s*true/,'production category persistence is enabled');
assert.ok(html.indexOf('js/categoryPersistenceAdapter.js')<html.indexOf('js/storage.js'),'adapter loads before storage module');
assert.ok(html.indexOf('js/categorySyncQueue.js')<html.indexOf('js/storage.js'),'queue loads before storage module');
assert.match(storage,/queueSave\(snapshot,options=\{\}\)[\s\S]*queueCategoryScopedSave\(snapshot,options\)/,'save options reach category persistence path');
assert.match(storage,/if\(options\?\.replaceAll\)[\s\S]*enqueueMasterReplacement/,'full imports use transactional master replacement');
assert.match(storage,/writeCategoryBaseline\(loaded\.master\)/,'successful cloud load persists a baseline for offline comparison');
assert.match(storage,/diffMasterAgainstBaseline\(master,baseline\)[\s\S]*pendingById\.set\(activeId,\{category,sortOrder:/,'ordinary saves reconcile all locally changed categories against the confirmed cloud baseline');
assert.match(storage,/const loaded=await window\.BADMINTON_CATEGORY_PERSISTENCE\.loadMaster\(this\.client,this\.clubId,masterTournament\?\.activeCategoryId\)[\s\S]*writeCategoryBaseline\(loaded\.master\)[\s\S]*Cloud saved; category baseline refresh deferred:/,'successful category queue flush refreshes the full confirmed cloud baseline');
assert.match(storage,/categorySaveWaiters:\[\]/,'debounced autosave tracks all pending confirmations');
assert.match(storage,/const waiters=this\.categorySaveWaiters\.splice\(0\)/,'debounced autosave drains all callers together');
assert.match(storage,/waiters\.forEach\(resolveSave=>resolveSave\(result\)\)/,'every coalesced save caller receives the actual sync result');
assert.match(storage,/readCategoryBootstrapQueue\(\)/,'offline saves before club resolution are persisted for later reconciliation');
assert.match(storage,/if\(bootstrap\.baseSnapshot&&Array\.isArray\(bootstrap\.baseSnapshot\.categories\)\)[\s\S]*this\.clearCategoryBootstrapQueue\(\);[\s\S]*Without a trustworthy baseline[\s\S]*this\.clearCategoryBootstrapQueue\(\);[\s\S]*local recovery record has been preserved/,'bootstrap recovery requires a baseline or matching cloud data before clearing the local recovery record');
assert.match(storage,/resumeCloudSync\(\)/,'network recovery retries cloud setup as well as pending writes');
assert.match(storage,/categoryPersistenceVersion/,'category migration marker is checked and preserved');
assert.match(storage,/legacyIsEmpty[\s\S]*if\(!seed&&legacyIsEmpty&&masterTournament\?\.categories\?\.length\)seed=masterTournament[\s\S]*if\(!seed&&!legacyIsEmpty\)throw new Error/,'local data can seed an empty legacy cloud only; unknown non-empty cloud snapshots fail safely');
assert.match(storage,/if\(!this\.appReady\|\|this\.profile\?\.approval_status!=='approved'\|\|!this\.tournamentId\)return \{status:'not-ready'\};\s*if\(this\.categoryModeEnabled\(\)\)/,'approval/startup guard remains before new persistence path');
assert.match(tournament,/category rename is metadata\/category-scoped work[\s\S]*saveLocal\(true\);[\s\S]*renderAll\(\);/,'category rename uses scoped persistence instead of full-master replacement');
assert.match(tournament,/allowEmptyOverwrite:true,allowCategoryRemoval:true/,'Reset All and JSON import explicitly authorize empty replacement and category removal');
assert.match(tournament,/saveLocal\(true,\{replaceAll:true,allowCategoryRemoval:true\}\)/,'category-list edits explicitly authorize removal of categories');
assert.match(tournament,/saveLocal\\(true,\\{replaceAll:true,allowCategoryRemoval:true\\}\\);[\\s\\S]*const active=getActiveCategoryRecord\\(\\)/,'category-count changes explicitly authorize category removal');
console.log('PASS: production category persistence is enabled; adapter and queue load before storage');
console.log('PASS: authenticated startup guard precedes category-mode startup');
console.log('PASS: imports and Reset All explicitly declare full data replacement; category rename uses scoped persistence');
console.log('PASS: ordinary saves pass through category-scoped queue path when enabled');
console.log('PASS: offline bootstrap snapshots are reconciled against the last confirmed cloud baseline');
