const assert=require('node:assert/strict');
const Queue=require('../js/categorySyncQueue.js');
const memoryStorage=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};};
const category=(id,name)=>({id,name,data:{teams:[{name}],results:[]}});
(async()=>{
 const storage=memoryStorage();const writes=[];let fail=false;let revision={AB:1,CD:4};let firstSaveHook=null;
 const adapter={async saveCategory(_client,{category,expectedRevision}){if(fail)throw new Error('network down');const id=category.id;writes.push({id,name:category.data.teams[0].name,expectedRevision});const next=(revision[id]||0)+1;revision[id]=next;if(firstSaveHook){const fn=firstSaveHook;firstSaveHook=null;fn();}return {status:'saved',revision:next};},async saveClubMetadata(_client,{clubName}){if(fail)throw new Error('network down');writes.push({id:'CLUB',name:clubName});return {status:'saved'};},async replaceMaster(_client,{master}){if(fail)throw new Error('network down');writes.push({id:'MASTER',name:master.clubName});return {status:'replaced',categoryCount:master.categories.length};},async loadMaster(){return {revisions:{AB:5,CD:2}};}};
 const queue=new Queue({adapter,client:{},clubId:'club',storage});
 queue.enqueueClubMetadata({clubName:'Club v1',sharedData:{date:'2026-10-04'}});
 queue.enqueueCategory(category('AB','AB v1'),{expectedRevision:1});
 queue.enqueueCategory(category('CD','CD v1'),{expectedRevision:4});
 queue.enqueueCategory(category('AB','AB v2'),{expectedRevision:1});
 assert.equal(queue.pendingCount(),3,'newer save coalesces within category but retains independent category and club operations');
 firstSaveHook=()=>queue.enqueueCategory(category('AB','AB v3'),{expectedRevision:1});
 const result=await queue.flush();
 assert.equal(result.status,'synced');assert.equal(queue.pendingCount(),0,'queue drains all operations after confirmation');
 assert.deepEqual(writes.map(w=>w.id),['CLUB','AB','CD','AB'],'changed category is retried if it changes during in-flight save, other category still saved');
 assert.equal(writes[3].expectedRevision,2,'in-flight newer operation is rebased on confirmed revision');
 queue.enqueueCategory(category('AB','AB offline'),{expectedRevision:revision.AB});fail=true;
 const failed=await queue.flush();assert.equal(failed.status,'pending');assert.equal(queue.pendingCount(),1,'network failure preserves queued operation');
 fail=false;const recovered=await queue.flush();assert.equal(recovered.status,'synced');assert.equal(queue.pendingCount(),0);
 queue.enqueueCategory(category('AB','before import'),{expectedRevision:revision.AB});
 queue.enqueueMasterReplacement({clubName:'Imported Club',date:'2026-10-04',activeCategoryId:'CD',categories:[category('CD','imported')]},{sharedData:{date:'2026-10-04'}});
 assert.equal(queue.pendingCount(),1,'whole-master import supersedes prior pending entity operations');
 const imported=await queue.flush();assert.equal(imported.status,'synced');assert.equal(writes.at(-1).id,'MASTER');assert.equal(queue.revisions.CD,2,'revisions refresh after a whole-master replacement');
 console.log('PASS: queue coalesces saves per category while retaining independent category operations');
 console.log('PASS: shared club metadata is queued separately from category payloads');
 console.log('PASS: a newer save during an in-flight write is retained and rebased');
 console.log('PASS: failed network write preserves queue and subsequent retry drains it');
 console.log('PASS: full import supersedes pending category operations and refreshes revisions');
})().catch(e=>{console.error(e);process.exit(1);});
