const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'../supabase/');
const sql=fs.readFileSync(path.join(root,'001_category_scoped_persistence.sql'),'utf8');
const backfill=fs.readFileSync(path.join(root,'005_backfill_valid_legacy_category_snapshots.sql'),'utf8');
const emptyOverwriteGuard=fs.readFileSync(path.join(root,'006_prevent_empty_category_overwrite.sql'),'utf8');
const masterOverwriteGuard=fs.readFileSync(path.join(root,'007_guard_master_replacement_empty_categories.sql'),'utf8');

assert.match(sql,/alter table public\.clubs\s+add column if not exists shared_data/i);
assert.match(sql,/create table if not exists public\.categories/i);
assert.match(sql,/alter table public\.categories enable row level security/i);
assert.match(sql,/private\.is_approved_user\(\)/i);
assert.match(sql,/private\.is_club_owner\(p_club_id\)/i);
assert.match(sql,/create or replace function public\.save_category_data/i);
assert.match(sql,/create or replace function public\.replace_club_master/i);
assert.match(sql,/create or replace function public\.save_club_metadata/i);
assert.match(sql,/v_shared := coalesce\(p_shared_data,'\{\}'::jsonb\) - 'categoryPersistenceVersion'/i,'routine metadata save cannot set the migration marker');
assert.match(sql,/jsonb_build_object\('categoryPersistenceVersion',1\)/i,'whole-master RPC writes a migration completion marker');
assert.equal((sql.match(/pg_advisory_xact_lock\(hashtextextended\(p_club_id::text, 0\)\)/gi)||[]).length,3,'category saves, metadata saves and master replacement share a transaction lock');
assert.match(sql,/coalesce\(p_expected_revision,0\) <> v_row\.revision/i);
assert.match(sql,/revoke all on function public\.save_category_data[\s\S]*from public, anon/i);
assert.match(sql,/revoke all on function public\.replace_club_master[\s\S]*from public, anon/i);
assert.doesNotMatch(sql,/drop table\s+public\.tournaments/i);
assert.doesNotMatch(sql,/truncate\s+public\./i);
assert.doesNotMatch(sql,/delete from public\.tournaments/i);

assert.match(backfill,/badmintonTournamentManagerMaster/i,'backfill accepts only the supported master snapshot format');
assert.match(backfill,/not exists\s*\(\s*select 1 from public\.categories existing where existing\.club_id = c\.id/i,'backfill skips clubs that already have category rows');
assert.match(backfill,/count\(distinct item\.category->>'id'\)/i,'backfill validates unique category IDs');
assert.match(backfill,/coalesce\(jsonb_typeof\(item\.category->'data'\), 'null'\) <> 'object'/i,'backfill rejects malformed category data');
assert.match(backfill,/on conflict \(club_id, legacy_category_id\) do nothing/i,'backfill is safe against duplicate category IDs');
assert.match(backfill,/categoryPersistenceVersion/i,'migration marker is written only after the full category set exists');
assert.doesNotMatch(backfill,/drop table\s+public\./i);
assert.doesNotMatch(backfill,/truncate\s+public\./i);
assert.doesNotMatch(backfill,/delete from public\.(tournaments|profiles|categories)/i);

assert.match(emptyOverwriteGuard,/create or replace function public\.save_category_data/i,'guard updates the existing category-save RPC');
assert.match(emptyOverwriteGuard,/for update/i,'guard reads the category row under a write lock');
assert.match(emptyOverwriteGuard,/refusing to overwrite populated category with an empty competition payload/i,'ordinary saves cannot erase all competition data from a populated category');
assert.match(emptyOverwriteGuard,/jsonb_array_length\(coalesce\(v_row\.data->'teams'/i,'guard detects existing competition records');
assert.match(emptyOverwriteGuard,/jsonb_array_length\(coalesce\(p_data->'teams'/i,'guard detects an empty incoming competition payload');
assert.match(emptyOverwriteGuard,/revoke all on function public\.save_category_data[\s\S]*from public, anon/i,'RPC permissions remain restricted');
assert.doesNotMatch(emptyOverwriteGuard,/drop table|truncate|delete from public\./i,'guard migration does not delete data or tables');
assert.match(masterOverwriteGuard,/allowEmptyOverwrite/i,'only explicitly intentional import/reset may bypass full-master empty-category protection');
assert.match(masterOverwriteGuard,/refusing full-master replacement that would erase populated category/i,'stale full-master snapshots cannot silently empty populated categories');
assert.match(masterOverwriteGuard,/refusing full-master replacement that omits populated category/i,'stale full-master snapshots cannot silently delete populated categories');
assert.match(masterOverwriteGuard,/allowCategoryRemoval/i,'category deletion requires explicit category-removal intent');
assert.match(masterOverwriteGuard,/shared_data=\(coalesce\(p_shared_data,'\{\}'::jsonb\) - 'allowEmptyOverwrite' - 'allowCategoryRemoval'\)/i,'intent flag is not persisted as club metadata');
assert.match(masterOverwriteGuard,/pg_advisory_xact_lock\(hashtextextended\(p_club_id::text, 0\)\)/i,'full-master guard shares the transaction lock');
assert.doesNotMatch(masterOverwriteGuard,/drop table|truncate/i,'full-master guard is additive and does not truncate tables');

console.log('PASS: category schema is additive and preserves the legacy tournaments table');
console.log('PASS: category RLS, authorization, revision checks and RPC grants are guarded');
console.log('PASS: legacy backfill accepts only complete supported snapshots and skips existing category sets');
console.log('PASS: backfill does not drop, truncate or delete user/tournament/category data');
console.log('PASS: full-master replacement rejects stale empty-category overwrites unless an explicit import/reset intent is supplied');
console.log('NOTE: static checks validate migration shape; production SQL was applied and verified directly on main.');
