const assert=require('node:assert/strict');const fs=require('node:fs');const sql=fs.readFileSync(require('node:path').join(__dirname,'../supabase/001_category_scoped_persistence.sql'),'utf8');
assert.match(sql,/alter table public\.clubs\s+add column if not exists shared_data/i);
assert.match(sql,/create table if not exists public\.categories/i);
assert.match(sql,/alter table public\.categories enable row level security/i);
assert.match(sql,/private\.is_approved_user\(\)/i);
assert.match(sql,/private\.is_club_owner\(p_club_id\)/i);
assert.match(sql,/create or replace function public\.save_category_data/i);
assert.match(sql,/create or replace function public\.replace_club_master/i);
assert.match(sql,/create or replace function public\.save_club_metadata/i);
assert.match(sql,/v_shared := coalesce\(p_shared_data,'\{\}'::jsonb\) - 'categoryPersistenceVersion'/i,'routine metadata save cannot set the migration marker');
assert.match(sql,/jsonb_build_object\('categoryPersistenceVersion',1\)/i,'whole-master RPC writes a migration completion marker');
assert.equal((sql.match(/pg_advisory_xact_lock\(hashtextextended\(p_club_id::text, 0\)\)/gi)||[]).length,3,'category saves, metadata saves and master replacement share a transaction lock');
assert.match(sql,/coalesce\(p_expected_revision,0\) <> v_row\.revision/i);
assert.match(sql,/revoke all on function public\.save_category_data[\s\S]*from public, anon/i);
assert.match(sql,/revoke all on function public\.replace_club_master[\s\S]*from public, anon/i);
assert.doesNotMatch(sql,/drop table\s+public\.tournaments/i);
assert.doesNotMatch(sql,/truncate\s+public\./i);
assert.doesNotMatch(sql,/delete from public\.tournaments/i);
console.log('PASS: additive migration only; legacy tournaments table is not dropped, truncated or deleted');
console.log('PASS: category RLS and authenticated owner/approval checks are present');
console.log('PASS: category writes and master replacement share a club-level advisory lock and revision check');
console.log('PASS: RPC execute privileges are revoked from public and anon');
console.log('NOTE: static checks are not a substitute for executing SQL on PostgreSQL staging.');
